stages:
  # ============================================================
  # DATA PROCESSING JOBS
  # ============================================================

  create_features:
    cmd: uv run python jobs/02_create_features.py
    deps:
      - jobs/02_create_features.py
      - data/raw_inputs/input_data_sun_heavy.xlsx
    outs:
      - data/processed/data_with_features.csv:
          cache: false

  # ============================================================
  # REPORT GENERATION
  # ============================================================

  report_01_eda:
    cmd: bash tools/generate_report.sh 01_eda reports_src/01_eda.py
    deps:
      - reports_src/01_eda.py
      - data/raw_inputs/input_data_sun_heavy.xlsx
      - tools/generate_report.sh
    outs:
      - reports/html/01_eda.html:
          cache: false
      - reports/markdown/01_eda.md:
          cache: false
      - reports/markdown/01_eda_files:
          cache: false

  report_03_analysis_features:
    cmd: bash tools/generate_report.sh 03_analysis_features reports_src/03_analysis_features.py
    deps:
      - reports_src/03_analysis_features.py
      - data/processed/data_with_features.csv
      - tools/generate_report.sh
    outs:
      - reports/html/03_analysis_features.html:
          cache: false
      - reports/markdown/03_analysis_features.md:
          cache: false
      - reports/markdown/03_analysis_features_files:
          cache: false
