stages:
  # ============================================================
  # DATA PROCESSING
  # ============================================================

  # 02: Create Features
  create_features:
    cmd: uv run python jobs/02_create_features.py
    deps:
      - jobs/02_create_features.py
      - data/raw_inputs/input_data_sun_heavy.csv
    outs:
      - data/processed/data_with_features.csv

  # 07: Train TabPFN vs XGBoost Multi-Horizon Models (Quarterly)
  train_07_tabpfn_xgboost_multi_horizon:
    cmd: uv run python jobs/07_tabpfn_xgboost_multi_horizon.py
    deps:
      - jobs/07_tabpfn_xgboost_multi_horizon.py
      - data/processed/data_with_features.csv
    metrics:
      - metrics/tabpfn_xgboost_evaluation.json:
          cache: false
    outs:
      - models/tabpfn_xgboost:
          cache: false
