stages:
  # ============================================================
  # REPORTS
  # ============================================================

  # 01: EDA Report
  report_01_eda:
    cmd: cd .. && bash tools/generate_report.sh 01_eda jobs/01_eda.py
    deps:
      - ../jobs/01_eda.py
      - ../data/raw_inputs/input_data_sun_heavy.csv
      - ../tools/generate_report.sh
    outs:
      - ../reports/html/01_eda.html:
          cache: false
      - ../reports/markdown/01_eda.md:
          cache: false
      - ../reports/markdown/01_eda_files:
          cache: false

  # 03: Analyse Features Report
  report_03_analyse_features:
    cmd: cd .. && bash tools/generate_report.sh 03_analyse_features jobs/03_analyse_features.py
    deps:
      - ../jobs/03_analyse_features.py
      - ../data/processed/data_with_features.csv
      - ../tools/generate_report.sh
    outs:
      - ../reports/html/03_analyse_features.html:
          cache: false
      - ../reports/markdown/03_analyse_features.md:
          cache: false
      - ../reports/markdown/03_analyse_features_files:
          cache: false

  # 04: Train and Evaluate Models (Jan-Nov vs Dec) - Report
  report_04_train_evaluate_jan_nov_dec:
    cmd: cd .. && bash tools/generate_report.sh 04_train_models_jan_nov_dec jobs/04_train_models_jan_nov_dec.py
    deps:
      - ../jobs/04_train_models_jan_nov_dec.py
      - ../data/processed/data_with_features.csv
      - ../tools/generate_report.sh
      - ../models/jan_nov_dec
      - ../metrics/jan_nov_dec_evaluation.json
    outs:
      - ../reports/html/04_train_models_jan_nov_dec.html:
          cache: false
      - ../reports/markdown/04_train_models_jan_nov_dec.md:
          cache: false
      - ../reports/markdown/04_train_models_jan_nov_dec_files:
          cache: false

  # 05: Train and Evaluate Models (Quarterly) - Report
  report_05_train_evaluate_quarterly:
    cmd: cd .. && bash tools/generate_report.sh 05_train_models_quarterly jobs/05_train_models_quarterly.py
    deps:
      - ../jobs/05_train_models_quarterly.py
      - ../data/processed/data_with_features.csv
      - ../tools/generate_report.sh
      - ../models/quarterly_split
      - ../metrics/quarterly_split_evaluation.json
    outs:
      - ../reports/html/05_train_models_quarterly.html:
          cache: false
      - ../reports/markdown/05_train_models_quarterly.md:
          cache: false
      - ../reports/markdown/05_train_models_quarterly_files:
          cache: false

  # 06: Train and Evaluate Multi-Horizon Models (Quarterly) - Report
  report_06_train_evaluate_multi_horizon_quarterly:
    cmd: cd .. && bash tools/generate_report.sh 06_multi_horizon_quarterly jobs/06_multi_horizon_quarterly.py
    deps:
      - ../jobs/06_multi_horizon_quarterly.py
      - ../data/processed/data_with_features.csv
      - ../tools/generate_report.sh
      - ../models/multi_horizon_quarterly
      - ../metrics/multi_horizon_quarterly_evaluation.json
    outs:
      - ../reports/html/06_multi_horizon_quarterly.html:
          cache: false
      - ../reports/markdown/06_multi_horizon_quarterly.md:
          cache: false
      - ../reports/markdown/06_multi_horizon_quarterly_files:
          cache: false
